# Generated by Django 5.1.3 on 2025-02-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=23, upload_to=''),
            preserve_default=False,
        ),
    ]
